version: "3"
services:
  covidzone:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        buildno: 1
        name: covidzone
    container_name: covidzone
    volumes:
      - './src:/src'
    ports:
      - '8081:8081'
    image: covidzone:latest
    restart: unless-stopped
